spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
  sql:
    init:
      data-locations: classpath:data-h2.sql
      mode: embedded