spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
  sql:
    init:
      data-locations: classpath:data-h2.sql
      mode: embedded


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json